# wrangler.toml
name               = "mcp-dploy"
main               = "src/index.ts"
compatibility_date = "2025-04-22"

# publish to your custom domain instead of workers.dev
workers_dev = false  
account_id  = "4c88d9185392b64fc4037c6c2cedf46e"             


# bind only the /mcp/* path on your domain
routes = [
  { pattern = "api.mcpdploy.com", custom_domain = true }
]

# (the rest of your config)
compatibility_flags = ["nodejs_compat"]

# Container configurations for user apps
[[containers]]
name = "node-app-container"
class_name = "NodeAppContainer"
image = "./containers/Dockerfile.node"
max_instances = 10
instance_type = "basic"

[[containers]]
name = "python-app-container"
class_name = "PythonAppContainer" 
image = "./containers/Dockerfile.python"
max_instances = 10
instance_type = "basic"

# Durable Object bindings for container management
[[durable_objects.bindings]]
name = "NODE_CONTAINERS"
class_name = "NodeAppContainer"

[[durable_objects.bindings]]
name = "PYTHON_CONTAINERS"
class_name = "PythonAppContainer"

# Database migration for Durable Objects
[[migrations]]
tag = "v1"
new_sqlite_classes = ["NodeAppContainer", "PythonAppContainer"]

[observability]
enabled = true

[alias]
"raw-body"     = "./src/empty.ts"
"content-type" = "./src/empty.ts"

[dev]
port = 3000



